# Generated by Django 3.0.5 on 2020-04-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=200)),
                ('match_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('steam_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PositionPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_position', models.IntegerField(default=0)),
                ('civilization', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balancer.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='balancer.Player')),
            ],
        ),
    ]
