# Generated by Django 3.0.5 on 2020-04-10 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0002_auto_20200410_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='civ',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='match',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='balancer.Match'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PositionPlayer',
        ),
    ]
