# Generated by Django 3.0.5 on 2020-04-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0003_auto_20200411_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['color']},
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='civ',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='balancer.Match'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('match', 'steam_id')},
        ),
    ]
