# Generated by Django 3.0.5 on 2020-04-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0005_auto_20200412_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='nom',
            new_name='name',
        ),
    ]
