# Generated by Django 3.0.5 on 2020-04-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balancer', '0006_auto_20200413_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='civ',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='steam_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
